//Get Todos
GET {{host}}/querytodos
Content-Type: application/json
Accept: application/json

{
}

###
//Create Todos
POST {{host}}/createTodo
Content-Type: application/json
Accept: application/json

{
  "text": "Binits TODO"
}
###
//Update Todo
PUT {{host}}/api/UpdateTodo
Content-Type: application/json
Accept: application/json

{
  "id": "b658015f49d04fd58f3fd6dc638a42dd",
  "text": "Make these changes again",
  "isFinished": "true"
}
###
DELETE {{host}}/api/DeleteTodo
Content-Type: application/json
Accept: application/json

{
  "id": "48aabed6c80e491fa13a51cd1371957f"
}
###
DELETE {{host}}/api/DeleteTodos
Content-Type: application/json
Accept: application/json

{
  "ids": ["b658015f49d04fd58f3fd6dc638a42dd","48aabed6c80e491fa13a51cd1371957f"]
}


